from __future__ import annotations

from .embeddings import embed_query_via_http, is_custom_http_embedding_provider
from .heuristic_router import (
    ARTICLE_REF_RE,
    LegalReference,
    QueryIntent,
    YEAR_COUNT_RE,
    build_query_variants,
    contains_normalized_phrase,
    dedupe_preserve_order,
    filter_specific_actor_labels,
    format_intent_summary,
    infer_employee_notice_period_reference,
    parse_reference_values,
    prioritize_issue_filters,
    query_asks_for_enumeration,
    query_asks_without_notice,
    route_query,
    route_query_heuristic,
)
from .query_router import query_intent_from_metadata, route_query_with_llm
from .rag.retrieval import (
    ContextAssembler,
    DEFAULT_MAX_CONTEXT_CHARS,
    DEFAULT_MAX_CONTEXT_TOKENS,
    DEFAULT_RERANKER_TOP_N,
    FORCED_REFERENCE_SCORE_MARGIN,
    HybridRetriever,
    POINT_REF_ALPHABET,
    POINT_REF_ORDER,
    QdrantPayloadRecordStore,
    QdrantSearcher,
    QueryEncoder,
    RECORD_SOURCE_QDRANT_PAYLOAD,
    RECORD_SOURCE_SQLITE,
    RRF_K,
    RULE_CONFIG,
    RecordStore,
    ReferenceExpander,
    RelevanceScorer,
    RetrievedRecord,
    RetrievalContext,
    RetrievalResult,
    SQLiteRecordStore,
    SUPPORTED_RECORD_SOURCES,
    SearchHit,
    SemanticReranker,
    actor_labels_for_sparse,
    build_context_block,
    build_expanded_context_text,
    context_article_key,
    context_looks_like_enumeration_parent,
    dedupe_records_by_chunk_id,
    diversify_contexts_by_article,
    env_flag,
    estimate_token_count,
    extend_context_with_records,
    format_context_for_prompt,
    load_manifest,
    point_ref_sort_key,
    record_from_qdrant_payload,
    record_reference_sort_key,
    resolve_record_source,
    select_contexts_for_prompt,
)


_RULE_CONFIG_EXPORTS = frozenset(("LEGAL_ISSUE_ARTICLE_MAP", "TERMINATION_ARTICLE_MAP"))
LEGAL_ISSUE_ARTICLE_MAP = RULE_CONFIG.LEGAL_ISSUE_ARTICLE_MAP
TERMINATION_ARTICLE_MAP = RULE_CONFIG.TERMINATION_ARTICLE_MAP


def __getattr__(name: str) -> object:
    if name in _RULE_CONFIG_EXPORTS:
        return getattr(RULE_CONFIG, name)
    raise AttributeError(name)


__all__ = [
    "ARTICLE_REF_RE",
    "ContextAssembler",
    "DEFAULT_MAX_CONTEXT_CHARS",
    "DEFAULT_MAX_CONTEXT_TOKENS",
    "DEFAULT_RERANKER_TOP_N",
    "FORCED_REFERENCE_SCORE_MARGIN",
    "HybridRetriever",
    "LEGAL_ISSUE_ARTICLE_MAP",
    "LegalReference",
    "POINT_REF_ALPHABET",
    "POINT_REF_ORDER",
    "QdrantPayloadRecordStore",
    "QdrantSearcher",
    "QueryEncoder",
    "QueryIntent",
    "RECORD_SOURCE_QDRANT_PAYLOAD",
    "RECORD_SOURCE_SQLITE",
    "RRF_K",
    "RULE_CONFIG",
    "RecordStore",
    "ReferenceExpander",
    "RelevanceScorer",
    "RetrievedRecord",
    "RetrievalContext",
    "RetrievalResult",
    "SQLiteRecordStore",
    "SUPPORTED_RECORD_SOURCES",
    "SearchHit",
    "SemanticReranker",
    "TERMINATION_ARTICLE_MAP",
    "YEAR_COUNT_RE",
    "actor_labels_for_sparse",
    "build_context_block",
    "build_expanded_context_text",
    "build_query_variants",
    "contains_normalized_phrase",
    "context_article_key",
    "context_looks_like_enumeration_parent",
    "dedupe_preserve_order",
    "dedupe_records_by_chunk_id",
    "diversify_contexts_by_article",
    "embed_query_via_http",
    "env_flag",
    "estimate_token_count",
    "extend_context_with_records",
    "filter_specific_actor_labels",
    "format_context_for_prompt",
    "format_intent_summary",
    "infer_employee_notice_period_reference",
    "is_custom_http_embedding_provider",
    "load_manifest",
    "parse_reference_values",
    "point_ref_sort_key",
    "prioritize_issue_filters",
    "query_asks_for_enumeration",
    "query_asks_without_notice",
    "query_intent_from_metadata",
    "record_from_qdrant_payload",
    "record_reference_sort_key",
    "resolve_record_source",
    "route_query",
    "route_query_heuristic",
    "route_query_with_llm",
    "select_contexts_for_prompt",
]
